@php($editingDeal = $editingDeal ?? null)
<div class="card content-card p-4"><div class="row g-4">
<div class="col-md-5"><label class="form-label fw-semibold" for="deal-country">Airline country</label><select class="form-select" id="deal-country" required><option value="">Select country first</option>@foreach($countries as $code => $country)<option value="{{ $code }}" @selected(old('country_code', $editingDeal?->airline?->country_code) === $code)>{{ $country }}</option>@endforeach</select></div>
<div class="col-md-7"><label class="form-label fw-semibold" for="deal-airline-search">Airline</label><input class="form-control" id="deal-airline-search" list="deal-airlines" value="{{ old('airline_label', $editingDeal?->airline ? $editingDeal->airline->name.' ('.$editingDeal->airline->code.')' : '') }}" placeholder="Select a country first, then search" autocomplete="off" required><input type="hidden" name="airline_id" id="deal-airline-id" value="{{ old('airline_id', $editingDeal?->airline_id) }}"><datalist id="deal-airlines"></datalist><small class="form-text">Only airlines registered in the selected country will be suggested.</small></div>
<div class="col-md-6"><label class="form-label fw-semibold">Origin airport <span class="text-secondary">(optional)</span></label><input class="form-control text-uppercase" name="origin_airport" maxlength="3" value="{{ old('origin_airport', $editingDeal?->origin_airport) }}" placeholder="LHR"><small class="form-text">Leave blank to apply to every origin.</small></div><div class="col-md-6"><label class="form-label fw-semibold">Destination airport <span class="text-secondary">(optional)</span></label><input class="form-control text-uppercase" name="destination_airport" maxlength="3" value="{{ old('destination_airport', $editingDeal?->destination_airport) }}" placeholder="LOS"><small class="form-text">Use airport codes for an exact route.</small></div>
<div class="col-md-6"><label class="form-label fw-semibold">Travel from</label><input class="form-control" type="date" name="travel_from" value="{{ old('travel_from', $editingDeal?->travel_from?->toDateString()) }}" required></div><div class="col-md-6"><label class="form-label fw-semibold">Travel until</label><input class="form-control" type="date" name="travel_until" value="{{ old('travel_until', $editingDeal?->travel_until?->toDateString()) }}" required></div>
<div class="col-md-4"><label class="form-label fw-semibold">Discount type</label><select class="form-select" name="discount_type" id="deal-discount-type"><option value="percentage" @selected(old('discount_type', $editingDeal?->discount_type ?? 'percentage') === 'percentage')>Percentage</option><option value="fixed" @selected(old('discount_type', $editingDeal?->discount_type) === 'fixed')>Fixed amount</option></select></div><div class="col-md-4"><label class="form-label fw-semibold">Discount value</label><input class="form-control" type="number" min="0.01" step="0.01" name="discount_value" value="{{ old('discount_value', $editingDeal?->discount_value) }}" required></div><div class="col-md-4"><label class="form-label fw-semibold">Currency <span class="text-secondary">(fixed only)</span></label><select class="form-select" name="discount_currency"><option value="">Not applicable</option>@foreach(['NGN','USD','GBP','EUR','CAD','ZAR','AED'] as $currency)<option value="{{ $currency }}" @selected(old('discount_currency', $editingDeal?->discount_currency) === $currency)>{{ $currency }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label fw-semibold">Priority</label><input class="form-control" type="number" min="0" name="priority" value="{{ old('priority', $editingDeal?->priority ?? 0) }}"><small class="form-text">Higher priority wins when rules overlap.</small></div><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="active" value="1" @checked(old('active', $editingDeal?->active ?? true))><span class="form-check-label">Deal is active</span></label></div></div><div class="alert alert-light border mt-4 mb-0"><i class="bi bi-info-circle me-2"></i>Deals are applied to live fares when the validating airline, route and departure date match.</div><div class="d-flex gap-2 justify-content-end mt-4"><a class="btn btn-outline-dark" href="{{ route('admin.flight-deals.index') }}">Cancel</a><button class="btn btn-karossy">Save flight deal</button></div></div>
@php($airlineJson = $airlines->map(fn ($airline) => ['id' => $airline->id, 'name' => $airline->name, 'code' => $airline->code, 'country_code' => $airline->country_code])->values())
@push('scripts')<script>
(()=>{const airlines=@json($airlineJson);const country=document.querySelector('#deal-country'),input=document.querySelector('#deal-airline-search'),id=document.querySelector('#deal-airline-id'),list=document.querySelector('#deal-airlines');const fill=()=>{const options=airlines.filter(a=>a.country_code===country.value);list.innerHTML=options.map(a=>`<option value="${a.name} (${a.code})" data-id="${a.id}"></option>`).join('');if(!options.some(a=>String(a.id)===id.value)) {id.value=''; input.value='';}};const choose=()=>{const found=airlines.find(a=>a.country_code===country.value&&(input.value===`${a.name} (${a.code})`||input.value.toLowerCase()===a.name.toLowerCase()||input.value.toUpperCase()===a.code));if(found)id.value=found.id;};country.addEventListener('change',fill);input.addEventListener('input',choose);fill();})();
</script>@endpush
