<div class="card content-card p-4"><div class="row g-4">
<div class="col-md-8"><label class="form-label fw-semibold">Package title</label><input class="form-control" name="title" value="{{ old('title',$holidayPackage->title??'') }}" required></div><div class="col-md-4"><label class="form-label fw-semibold">Destination</label><input class="form-control" name="destination" value="{{ old('destination',$holidayPackage->destination??'') }}" required></div>
<div class="col-md-4"><label class="form-label fw-semibold">Country / region</label><input class="form-control" name="country" value="{{ old('country',$holidayPackage->country??'') }}"></div><div class="col-md-8"><label class="form-label fw-semibold">Short tagline</label><input class="form-control" name="tagline" value="{{ old('tagline',$holidayPackage->tagline??'') }}"></div>
<div class="col-12"><label class="form-label fw-semibold">Description</label><textarea class="form-control" name="summary" rows="4">{{ old('summary',$holidayPackage->summary??'') }}</textarea></div>
<div class="col-md-2"><label class="form-label fw-semibold">Nights</label><input class="form-control" type="number" min="1" name="nights" value="{{ old('nights',$holidayPackage->nights??5) }}" required></div><div class="col-md-2"><label class="form-label fw-semibold">Days</label><input class="form-control" type="number" min="2" name="days" value="{{ old('days',$holidayPackage->days??6) }}" required></div><div class="col-md-2"><label class="form-label fw-semibold">Currency</label><select class="form-select" name="currency"><option>NGN</option><option @selected(old('currency',$holidayPackage->currency??'NGN')==='USD')>USD</option></select></div><div class="col-md-3"><label class="form-label fw-semibold">Starting price</label><input class="form-control" type="number" step="0.01" min="0" name="price" value="{{ old('price',isset($holidayPackage)?number_format($holidayPackage->price_minor/100,2,'.',''):'') }}" required></div><div class="col-md-3"><label class="form-label fw-semibold">Cover image</label><input class="form-control" type="file" accept="image/*" name="image"></div>
<div class="col-md-6"><label class="form-label fw-semibold">Available from</label><input class="form-control" type="date" name="starts_at" value="{{ old('starts_at',isset($holidayPackage)&&$holidayPackage->starts_at?$holidayPackage->starts_at->toDateString():'') }}"></div><div class="col-md-6"><label class="form-label fw-semibold">Available until</label><input class="form-control" type="date" name="ends_at" value="{{ old('ends_at',isset($holidayPackage)&&$holidayPackage->ends_at?$holidayPackage->ends_at->toDateString():'') }}"></div>
<div class="col-12"><label class="form-label fw-semibold">Inclusions <small class="text-secondary">one per line</small></label><textarea class="form-control" rows="7" name="inclusions_text">{{ old('inclusions_text',isset($holidayPackage)?implode("\n",$holidayPackage->inclusions??[]):'Flights\nHotel accommodation\nAirport transfer\nDedicated travel support') }}</textarea></div>
<div class="col-12 d-flex flex-wrap gap-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="featured" value="1" @checked(old('featured',$holidayPackage->featured??false))><span class="form-check-label">Feature on homepage</span></label><label class="form-check"><input class="form-check-input" type="checkbox" name="active" value="1" @checked(old('active',$holidayPackage->active??true))><span class="form-check-label">Available publicly</span></label></div>
</div><div class="d-flex gap-2 justify-content-end mt-4"><a class="btn btn-outline-dark" href="{{ route('admin.holidays.index') }}">Cancel</a><button class="btn btn-karossy">Save package</button></div></div>
