@extends('layouts.admin')
@section('title', 'Book on Hold Settings')
@section('content')
<header class="mb-4"><p class="text-danger fw-semibold mb-1">SETTINGS</p><h1 class="h3 fw-bold mb-2">Book on Hold</h1><p class="text-secondary mb-0">Control pay-later reservations and the bank details printed on customer invoices.</p></header>
<form method="POST" action="{{ route('admin.settings.booking-hold.update') }}" class="card content-card"><div class="card-body p-4">@csrf @method('PUT')
<div class="form-check form-switch mb-4"><input type="hidden" name="enabled" value="0"><input class="form-check-input" type="checkbox" name="enabled" value="1" @checked($settings->enabled)><label class="form-check-label"><strong>Enable Book on Hold</strong><small class="d-block text-secondary">Allow customers to reserve eligible flights without paying immediately.</small></label></div>
<div class="mb-4"><label class="form-label">Hold timeout</label><div class="input-group"><input class="form-control" type="number" name="timeout_hours" min="1" max="168" value="{{ old('timeout_hours', $settings->timeout_hours) }}"><span class="input-group-text">hours</span></div></div>
<div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-2 mb-3"><div><h2 class="h5 mb-1">Bank transfer details</h2><p class="text-secondary mb-0">Invoices use the account matching the currency selected by the customer.</p></div><span class="badge rounded-pill text-bg-light border px-3 py-2">Currency based — not location based</span></div>
<div class="row g-4">
    <div class="col-xl-6"><section class="border rounded-4 p-3 p-lg-4 h-100"><div class="d-flex align-items-center gap-3 mb-3"><span class="badge rounded-pill text-bg-success px-3 py-2">NGN</span><div><h3 class="h6 mb-0">Naira account</h3><small class="text-secondary">Shown on NGN booking invoices</small></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Bank name</label><input class="form-control" name="ngn_bank_name" value="{{ old('ngn_bank_name', $settings->ngn_bank_name ?: $settings->bank_name) }}"></div><div class="col-md-6"><label class="form-label">Account name</label><input class="form-control" name="ngn_account_name" value="{{ old('ngn_account_name', $settings->ngn_account_name ?: $settings->account_name) }}"></div><div class="col-md-6"><label class="form-label">Account number</label><input class="form-control" name="ngn_account_number" value="{{ old('ngn_account_number', $settings->ngn_account_number ?: $settings->account_number) }}"></div><div class="col-md-6"><label class="form-label">Sort code / other identifier</label><input class="form-control" name="ngn_sort_code" value="{{ old('ngn_sort_code', $settings->ngn_sort_code ?: $settings->sort_code) }}"></div></div></section></div>
    <div class="col-xl-6"><section class="border rounded-4 p-3 p-lg-4 h-100"><div class="d-flex align-items-center gap-3 mb-3"><span class="badge rounded-pill text-bg-primary px-3 py-2">USD</span><div><h3 class="h6 mb-0">US dollar account</h3><small class="text-secondary">Shown on USD booking invoices</small></div></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Bank name</label><input class="form-control" name="usd_bank_name" value="{{ old('usd_bank_name', $settings->usd_bank_name) }}"></div><div class="col-md-6"><label class="form-label">Account name</label><input class="form-control" name="usd_account_name" value="{{ old('usd_account_name', $settings->usd_account_name) }}"></div><div class="col-md-6"><label class="form-label">Account number</label><input class="form-control" name="usd_account_number" value="{{ old('usd_account_number', $settings->usd_account_number) }}"></div><div class="col-md-6"><label class="form-label">Routing / SWIFT / identifier</label><input class="form-control" name="usd_sort_code" value="{{ old('usd_sort_code', $settings->usd_sort_code) }}"></div></div></section></div>
</div>
<button class="btn btn-karossy mt-4" type="submit">Save settings</button></div></form>
@endsection
