@extends('layouts.admin')

@section('title', 'New User')

@section('content')
<header class="mb-4"><a href="{{ route('admin.users.index') }}" class="text-decoration-none small"><i class="bi bi-arrow-left me-1"></i>Accounts</a><p class="text-danger fw-semibold mt-3 mb-1">ACCOUNT MANAGEMENT</p><h1 class="h3 fw-bold mb-2">Create account</h1><p class="text-secondary mb-0">Add an administrator, B2B travel agent or B2C customer account.</p></header>

<form method="POST" action="{{ route('admin.users.store') }}">@csrf
<div class="row g-4"><div class="col-xl-8"><div class="card content-card"><div class="card-body p-4 p-lg-5">
    <h2 class="h5 mb-3">Account type</h2>
    <div class="row g-3 mb-4">
        <div class="col-md-4"><input class="btn-check account-type-input" type="radio" name="account_type" id="account-admin" value="admin" @checked(old('account_type', 'admin') === 'admin')><label class="account-type-card" for="account-admin"><span class="account-type-icon"><i class="bi bi-shield-lock-fill"></i></span><span><strong>Administrator</strong><small>Internal staff with assigned roles and permissions.</small></span><i class="bi bi-check-circle-fill account-type-check"></i></label></div>
        <div class="col-md-4"><input class="btn-check account-type-input" type="radio" name="account_type" id="account-b2b" value="b2b" @checked(old('account_type') === 'b2b')><label class="account-type-card" for="account-b2b"><span class="account-type-icon"><i class="bi bi-buildings-fill"></i></span><span><strong>B2B Business</strong><small>Agency or corporate travel account with isolated data.</small></span><i class="bi bi-check-circle-fill account-type-check"></i></label></div>
        <div class="col-md-4"><input class="btn-check account-type-input" type="radio" name="account_type" id="account-b2c" value="b2c" @checked(old('account_type') === 'b2c')><label class="account-type-card" for="account-b2c"><span class="account-type-icon"><i class="bi bi-person-fill"></i></span><span><strong>B2C Customer</strong><small>Individual traveller booking directly with Karossy.</small></span><i class="bi bi-check-circle-fill account-type-check"></i></label></div>
    </div>
    @error('account_type')<div class="text-danger small mb-3">{{ $message }}</div>@enderror

    <h2 class="h5 mb-3">User details</h2>
    <div class="row g-3">
        <div class="col-md-6"><label for="name" class="form-label fw-semibold">Full name</label><input id="name" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="email" class="form-label fw-semibold">Email address</label><input id="email" type="email" name="email" value="{{ old('email') }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12 company-field {{ old('account_type', 'b2c') === 'b2b' ? '' : 'd-none' }}"><label for="company_name" class="form-label fw-semibold">Company name</label><input id="company_name" name="company_name" value="{{ old('company_name') }}" class="form-control @error('company_name') is-invalid @enderror" placeholder="Business or agency name">@error('company_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="password" class="form-label fw-semibold">Temporary password</label><input id="password" type="password" name="password" class="form-control @error('password') is-invalid @enderror" required autocomplete="new-password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">At least 8 characters with letters and numbers.</div></div>
        <div class="col-md-6"><label for="password_confirmation" class="form-label fw-semibold">Confirm password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-control" required autocomplete="new-password"></div>
        <div class="col-md-6"><label for="status" class="form-label fw-semibold">Account status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror"><option value="active" @selected(old('status', 'active') === 'active')>Active</option><option value="pending" @selected(old('status') === 'pending')>Pending</option><option value="suspended" @selected(old('status') === 'suspended')>Suspended</option></select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label for="currency_code" class="form-label fw-semibold">Currency code</label><select id="currency_code" name="currency_code" class="form-select @error('currency_code') is-invalid @enderror" required>@foreach(['NGN' => 'NGN — Nigerian Naira', 'USD' => 'USD — US Dollar', 'GBP' => 'GBP — British Pound', 'EUR' => 'EUR — Euro', 'CAD' => 'CAD — Canadian Dollar', 'ZAR' => 'ZAR — South African Rand', 'AED' => 'AED — UAE Dirham'] as $code => $label)<option value="{{ $code }}" @selected(old('currency_code', 'NGN') === $code)>{{ $label }}</option>@endforeach</select>@error('currency_code')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Prices and account reports will default to this ISO currency.</div></div>
    </div>
</div></div></div>
<aside class="col-xl-4"><div class="card content-card"><div class="card-body p-4"><div class="admin-role-fields {{ old('account_type', 'admin') === 'admin' ? '' : 'd-none' }}"><h2 class="h5 mb-1">Administrative roles</h2><p class="small text-secondary">Choose what this administrator can see and manage.</p>@forelse($roles as $role)<div class="form-check border-top py-3"><input class="form-check-input" type="checkbox" name="role_ids[]" value="{{ $role->id }}" id="role-{{ $role->id }}" @checked(collect(old('role_ids', []))->contains($role->id))><label class="form-check-label" for="role-{{ $role->id }}"><strong class="d-block">{{ $role->label }}</strong><code>{{ $role->name }}</code></label></div>@empty<div class="alert alert-light border small">No roles are available.</div>@endforelse</div><div class="b2b-access-note {{ old('account_type') === 'b2b' ? '' : 'd-none' }}"><h2 class="h5 mb-2">B2B access</h2><p class="small text-secondary mb-0">The B2B Travel Agent role is assigned automatically. This account sees only its own customers, searches and bookings.</p></div><div class="b2c-access-note {{ old('account_type') === 'b2c' ? '' : 'd-none' }}"><h2 class="h5 mb-2">B2C access</h2><p class="small text-secondary mb-0">Customer accounts do not receive access to the operations dashboard.</p></div></div></aside></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-karossy px-4">Create user</button><a href="{{ route('admin.users.index') }}" class="btn btn-outline-secondary px-4">Cancel</a></div>
</form>
@endsection

@push('scripts')<script>function updateAccountFields(){const type=document.querySelector('.account-type-input:checked')?.value;document.querySelector('.company-field')?.classList.toggle('d-none',type!=='b2b');document.querySelector('#company_name')?.toggleAttribute('required',type==='b2b');document.querySelector('.admin-role-fields')?.classList.toggle('d-none',type!=='admin');document.querySelector('.b2b-access-note')?.classList.toggle('d-none',type!=='b2b');document.querySelector('.b2c-access-note')?.classList.toggle('d-none',type!=='b2c');}document.querySelectorAll('.account-type-input').forEach(input=>input.addEventListener('change',updateAccountFields));updateAccountFields();</script>@endpush
