<div class="card content-card"><div class="card-body p-4 p-lg-5"><div class="row g-4">
    <div class="col-lg-8"><label class="form-label" for="name">Service name</label><input class="form-control" id="name" name="name" value="{{ old('name', $visa->name ?? '') }}" placeholder="Tourist Visa · Standard" maxlength="150" required></div>
    <div class="col-lg-4"><label class="form-label" for="visa_type">Visa type</label><select class="form-select" id="visa_type" name="visa_type" required>@foreach($visaTypes as $value => $label)<option value="{{ $value }}" @selected(old('visa_type', $visa->visa_type ?? 'sticker') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-5"><label class="form-label" for="passport_country">Passport / origin country</label><input class="form-control" id="passport_country" name="passport_country" value="{{ old('passport_country', $visa->passport_country ?? '') }}" placeholder="Nigeria or Any" maxlength="120" required></div>
    <div class="col-md-1"><label class="form-label" for="passport_country_code">Code</label><input class="form-control text-uppercase" id="passport_country_code" name="passport_country_code" value="{{ old('passport_country_code', $visa->passport_country_code ?? '') }}" maxlength="2" placeholder="NG"></div>
    <div class="col-md-5"><label class="form-label" for="country">Destination country</label><input class="form-control" id="country" name="country" value="{{ old('country', $visa->country ?? '') }}" placeholder="Austria" maxlength="120" required></div>
    <div class="col-md-1"><label class="form-label" for="destination_country_code">Code</label><input class="form-control text-uppercase" id="destination_country_code" name="destination_country_code" value="{{ old('destination_country_code', $visa->destination_country_code ?? '') }}" maxlength="2" placeholder="AT"></div>
    <div class="col-md-4"><label class="form-label" for="validity">Validity / permitted stay</label><input class="form-control" id="validity" name="validity" value="{{ old('validity', $visa->validity ?? '') }}" placeholder="Up to 90 days within 180 days" required></div>
    <div class="col-md-4"><label class="form-label" for="processing_time">Processing time shown to customer</label><input class="form-control" id="processing_time" name="processing_time" value="{{ old('processing_time', $visa->processing_time ?? '') }}" placeholder="14–28 business days" required></div>
    <div class="col-md-4"><label class="form-label" for="duration_days">Internal processing days</label><input class="form-control" id="duration_days" name="duration_days" type="number" min="1" max="365" value="{{ old('duration_days', $visa->duration_days ?? '') }}" required></div>
    <div class="col-md-2"><label class="form-label" for="currency">Currency</label><select class="form-select" id="currency" name="currency"><option value="NGN" @selected(old('currency', $visa->currency ?? 'NGN') === 'NGN')>NGN</option><option value="USD" @selected(old('currency', $visa->currency ?? 'NGN') === 'USD')>USD</option></select></div>
    <div class="col-md-5"><label class="form-label" for="fee_cents">Visa fee (minor units)</label><input class="form-control" id="fee_cents" name="fee_cents" type="number" min="0" step="1" value="{{ old('fee_cents', $visa->fee_cents ?? '') }}" required><small class="text-secondary">NGN 194,250.00 is entered as 19425000.</small></div>
    <div class="col-md-5"><label class="form-label" for="consultation_fee_cents">Optional consultation fee (minor units)</label><input class="form-control" id="consultation_fee_cents" name="consultation_fee_cents" type="number" min="0" step="1" value="{{ old('consultation_fee_cents', $visa->consultation_fee_cents ?? 0) }}"></div>
    <div class="col-12"><label class="form-label" for="summary">Short customer summary</label><textarea class="form-control" id="summary" name="summary" rows="2" maxlength="2000" placeholder="A concise description of this visa service…">{{ old('summary', $visa->summary ?? '') }}</textarea></div>
    <div class="col-lg-6"><label class="form-label" for="requirements_text">Required documents <small class="text-secondary">one per line</small></label><textarea class="form-control" id="requirements_text" name="requirements_text" rows="8" required>{{ old('requirements_text', isset($visa) ? implode("\n", $visa->requirements_list ?: preg_split('/\r\n|\r|\n/', (string) $visa->requirements)) : '') }}</textarea></div>
    <div class="col-lg-6"><label class="form-label" for="important_information_text">Important information <small class="text-secondary">one per line</small></label><textarea class="form-control" id="important_information_text" name="important_information_text" rows="8">{{ old('important_information_text', isset($visa) ? implode("\n", $visa->important_information ?? []) : '') }}</textarea></div>
    <div class="col-12 d-flex flex-wrap gap-4"><div class="form-check form-switch"><input type="hidden" name="active" value="0"><input class="form-check-input" id="active" name="active" type="checkbox" value="1" @checked((bool) old('active', $visa->active ?? true))><label class="form-check-label" for="active">Available to customers</label></div><div class="form-check form-switch"><input type="hidden" name="featured" value="0"><input class="form-check-input" id="featured" name="featured" type="checkbox" value="1" @checked((bool) old('featured', $visa->featured ?? false))><label class="form-check-label" for="featured">Feature this destination</label></div></div>
</div></div><div class="card-footer bg-white border-0 px-4 px-lg-5 pb-4 d-flex flex-wrap justify-content-end gap-2"><a class="btn btn-light" href="{{ route('admin.visas.index') }}">Cancel</a><button class="btn btn-karossy" type="submit"><i class="bi bi-check2 me-2"></i>{{ isset($visa) ? 'Save changes' : 'Create visa service' }}</button></div></div>
