@extends('layouts.public')
@section('title', 'Visa services')
@section('content')
<section class="visa-hero"><div class="container public-container"><div class="visa-hero-copy"><span class="public-eyebrow"><i class="bi bi-passport-fill"></i> Guided visa support</span><h1>Start your visa journey with clarity.</h1><p>Check the exact service, documents, processing time and customer price configured by the Karossy visa team.</p></div><div class="visa-search-card"><h2>Check visa eligibility</h2><form action="{{ route('visas.results') }}" method="GET" class="visa-search-form" novalidate data-visa-search><label><span>Passport country</span><select name="passport_country" required data-searchable-select data-search-placeholder="Search passport country"><option value="">Select your passport country</option>@foreach($passportCountries as $country)<option>{{ $country }}</option>@endforeach</select></label><label><span>Destination</span><select name="destination" required data-searchable-select data-search-placeholder="Search destination"><option value="">Where are you travelling to?</option>@foreach($destinations as $country)<option>{{ $country }}</option>@endforeach</select></label><label class="visa-travellers"><span>Travellers</span><span class="visa-counter"><button type="button" data-count-minus aria-label="Remove traveller">−</button><input name="travellers" value="1" readonly><button type="button" data-count-plus aria-label="Add traveller">+</button></span></label><button class="btn btn-karossy" type="submit">Check requirements <i class="bi bi-arrow-right"></i></button></form></div></div></section>
<section class="visa-section"><div class="container public-container"><div class="section-heading centered"><span class="public-eyebrow">Simple and supported</span><h2>How it works</h2></div><div class="visa-step-grid">@foreach([['search','Check requirements','See the visa type, documents, timing and exact customer price.'],['credit-card','Pay & apply','Pay securely, then submit the requested application documents.'],['passport','Track your application','Follow each step while the Karossy team coordinates your application.']] as $i=>$step)<article><span>{{ $i+1 }}</span><i class="bi bi-{{ $step[0] }}"></i><h3>{{ $step[1] }}</h3><p>{{ $step[2] }}</p></article>@endforeach</div></div></section>
<section class="visa-section visa-section-soft"><div class="container public-container"><div class="section-heading centered"><span class="public-eyebrow">Options for your journey</span><h2>Visa support we provide</h2></div><div class="visa-type-grid"><article><i class="bi bi-credit-card"></i><h3>eVisa</h3><p>A guided digital application where the destination supports online processing.</p><span>Online workflow</span></article><article><i class="bi bi-file-earmark-text"></i><h3>Sticker visa</h3><p>Document guidance and application coordination for embassy-issued visas.</p><span>Embassy submission</span></article><article><i class="bi bi-clock-history"></i><h3>Visa consultation</h3><p>One-to-one document review, interview preparation and application guidance.</p><span>Optional add-on</span></article></div></div></section>
@if($featuredVisas->isNotEmpty())<section class="visa-section"><div class="container public-container"><div class="section-heading"><span class="public-eyebrow">Popular destinations</span><h2>Start with a featured visa service</h2></div><div class="visa-feature-grid">@foreach($featuredVisas as $visa)<a href="{{ route('visas.show', ['visa'=>$visa,'travellers'=>1]) }}"><span class="country-flag">{{ $visa->destination_country_code ? mb_chr(127397 + ord($visa->destination_country_code[0])).mb_chr(127397 + ord($visa->destination_country_code[1])) : '🌍' }}</span><span><strong>{{ $visa->country }}</strong><small>{{ $visa->processing_time }}</small></span><i class="bi bi-arrow-up-right"></i></a>@endforeach</div></div></section>@endif
@endsection
@push('scripts')<script>document.querySelectorAll('[data-visa-search]').forEach(form=>{const input=form.querySelector('[name="travellers"]');form.querySelector('[data-count-minus]').onclick=()=>input.value=Math.max(1,Number(input.value)-1);form.querySelector('[data-count-plus]').onclick=()=>input.value=Math.min(10,Number(input.value)+1);form.addEventListener('submit',e=>{let firstInvalid=null;form.querySelectorAll('select[data-searchable-select]').forEach(field=>{const invalid=!field.value;field.closest('label').classList.toggle('is-invalid',invalid);if(invalid&&!firstInvalid)firstInvalid=field;});if(firstInvalid){e.preventDefault();firstInvalid.closest('label')?.querySelector('.searchable-select-input')?.focus();}});});</script>@endpush
