@php
    $global = old('is_karossey_rule', $rule->is_karossey_rule ?? false);
@endphp
<div class="row g-4">
    <div class="col-lg-4"><label class="form-label fw-semibold" for="airline_code">Airline IATA code</label><input id="airline_code" name="airline_code" class="form-control text-uppercase @error('airline_code') is-invalid @enderror" maxlength="3" value="{{ old('airline_code', $rule->airline_code ?? '') }}" placeholder="BA" data-airline-code @disabled($global)>@error('airline_code')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Use the airline's two- or three-character IATA code.</div></div>
    <div class="col-lg-8"><label class="form-label fw-semibold" for="title">Rule title</label><input id="title" name="title" class="form-control @error('title') is-invalid @enderror" maxlength="160" value="{{ old('title', $rule->title ?? '') }}" placeholder="Changes and cancellations" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label fw-semibold" for="content">Rule details shown at checkout</label><textarea id="content" name="content" class="form-control @error('content') is-invalid @enderror" rows="8" required placeholder="Explain the fare, cancellation, baggage or Karossy conditions clearly.">{{ old('content', $rule->content ?? '') }}</textarea>@error('content')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label fw-semibold" for="effective_from">Effective from</label><input id="effective_from" name="effective_from" type="datetime-local" class="form-control @error('effective_from') is-invalid @enderror" value="{{ old('effective_from', isset($rule) && $rule->effective_from ? $rule->effective_from->format('Y-m-d\TH:i') : '') }}">@error('effective_from')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label fw-semibold" for="effective_to">Effective until</label><input id="effective_to" name="effective_to" type="datetime-local" class="form-control @error('effective_to') is-invalid @enderror" value="{{ old('effective_to', isset($rule) && $rule->effective_to ? $rule->effective_to->format('Y-m-d\TH:i') : '') }}">@error('effective_to')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12 d-flex flex-wrap gap-4"><label class="form-check"><input class="form-check-input" name="is_karossey_rule" type="checkbox" value="1" @checked($global) data-global-rule><span class="form-check-label"><strong>Karossy global rule</strong><small class="d-block text-secondary">Show this for every airline at checkout.</small></span></label><label class="form-check"><input class="form-check-input" name="active" type="checkbox" value="1" @checked(old('active', $rule->active ?? true))><span class="form-check-label"><strong>Active</strong><small class="d-block text-secondary">Inactive rules are never shown to customers.</small></span></label></div>
</div>
@push('scripts')<script>(()=>{const global=document.querySelector('[data-global-rule]');const airline=document.querySelector('[data-airline-code]');const sync=()=>{airline.disabled=global.checked;if(global.checked) airline.value='KAROSSY';else if(airline.value==='KAROSSY') airline.value='';};global?.addEventListener('change',sync);sync();})();</script>@endpush
