@extends('layouts.admin')
@section('title', 'Fare Rules')
@section('content')
@php
$sortUrl=fn(string $column)=>route('admin.fair-rules.index',array_merge(request()->query(),['sort'=>$column,'direction'=>request('sort')===$column&&request('direction')!=='desc'?'desc':'asc']));
$sortIcon=fn(string $column)=>request('sort')===$column?(request('direction')==='desc'?'bi-sort-down':'bi-sort-up'):'bi-arrow-down-up';
@endphp
<header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="text-danger fw-semibold mb-1">FLIGHTS</p><h1 class="h3 fw-bold mb-1">Fare rules</h1><p class="text-secondary mb-0">Airline conditions and Karossy rules automatically shown for the selected fare.</p></div><a class="btn btn-karossy" href="{{ route('admin.fair-rules.create') }}"><i class="bi bi-plus-lg"></i> New rule</a></header>
<div class="card content-card admin-table-card"><div class="card-header bg-white border-0 p-3 p-md-4"><form method="GET" class="row g-2"><div class="col-lg-7"><div class="input-group admin-table-search"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Search airline code, title or rule"></div></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn admin-search-button" type="submit">Filter</button></div></form></div>
<div class="table-responsive"><table class="table admin-data-table align-middle mb-0"><thead><tr><th class="ps-4"><a href="{{ $sortUrl('airline_code') }}">Scope <i class="bi {{ $sortIcon('airline_code') }}"></i></a></th><th><a href="{{ $sortUrl('title') }}">Rule <i class="bi {{ $sortIcon('title') }}"></i></a></th><th>Effective period</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>@forelse($rules as $rule)<tr><td class="ps-4"><span class="badge rounded-pill {{ $rule->is_karossey_rule?'badge-system':'badge-custom' }}">{{ $rule->is_karossey_rule?'All airlines':$rule->airline_code }}</span></td><td><strong>{{ $rule->title }}</strong><small class="d-block text-secondary text-truncate" style="max-width:34rem">{{ $rule->content }}</small></td><td><small>{{ $rule->effective_from?->format('d M Y') ?? 'Immediately' }} — {{ $rule->effective_to?->format('d M Y') ?? 'No expiry' }}</small></td><td><span class="status-dot {{ $rule->active?'ready':'pending' }}"></span>{{ $rule->active?'Active':'Inactive' }}</td><td class="text-end pe-4"><div class="table-actions"><a class="btn table-action-btn" href="{{ route('admin.fair-rules.edit',$rule) }}"><i class="bi bi-pencil"></i><span>Edit</span></a><form method="POST" action="{{ route('admin.fair-rules.destroy',$rule) }}" data-confirm="Delete this fare rule?">@csrf @method('DELETE')<button class="btn table-action-btn table-action-danger"><i class="bi bi-trash3"></i><span>Delete</span></button></form></div></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">No fare rules found.</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white border-0 p-3 p-md-4 d-flex justify-content-between"><small class="text-secondary">{{ $rules->total() }} rules</small>{{ $rules->links() }}</div></div>
@endsection
